Garagist:
  Mautic:
    routeArgument:
      htmlTemplate: emailHtml
      plaintextTemplate: emailPlain
    api:
      baseUrl: null
      userName: null
      password: null
    publicUrl: null
    enableTracking: false
    forms:
      hideIds: []

    # Add here the ID fo the newsletter category
    newsletterCategoryId: null

    # Settings for email segments
    segment:
      mapping: null

      # Add here to segments to choose from on creation
      # choose: [1, 2]
      choose: null

      # Add here the segment ID of the Mautic segment who contains not confirmed contacts
      unconfirmed: null

    # Make actions configurable
    jobs:
      transactions:
        publishAndSend:
          up:
            - publish
            - send
          down:
            - unpublish
    actions:
      publishAndSend: false
      unpublishAndUpdate: false

      delete: true
      publish: true
      unpublish: true
      send: true
      update: true
