Garagist:
  Mautic:
    api:
      baseUrl: null
      userName: null
      password: null
      ignoreHttpsErrors: false
    publicUrl: null
    enableTracking: true
    # Can be javascript, iframe, plain or api
    embedType: javascript
    apiRenderer: null
    removeEmailIfNodeRemoved: true
