Garagist:
  Mautic:
    routeArgument:
      htmlTemplate: email
      plaintextTemplate: plaintext
    api:
      baseUrl: null
      userName: null
      password: null
    publicUrl: null
    enableTracking: false
    mail:
      # Injects the tracking pixel from Mautic right before the closing `body` tag.
      trackingPixel: '<img src="{tracking_pixel}" alt="" />'
    form:
      # Add here the IDs of the forms you want to hide
      # You can pass an array (eg. [1, 2, 3]) or an integer
      hide: null

    category:
      # Add here the ID of the category you want to use for the newsletter
      newsletter: null

    testMail:
      # Add here the email addresses you want to use for testing
      # You can pass an array (eg. ['test@mail.example', 'user@mail.example']) or an string (eg. 'test@mail.example')
      recipients: null

    # Settings for email segments
    segment:
      # If a segment is preSelected from the creation/edit dialog, the user can't unselect it
      lockPreSelected: true

      # Segments (Mautic ID) that are preSelected in the creation/edit dialog.
      # But you can also define an array/object to handle the segment in your own data provider
      preSelected: null

      # Segments (Mautic ID) that can be selected from on creation/edit dialog
      # You can pass an array (eg. [1, 2, 3]) or an integer
      selectable: null

      # Add here the IDs of the segments you want to hide (eg. for unconfirmed contacts)
      # You can pass an array (eg. [1, 2, 3]) or an integer
      hide: null

    action:
      delete: true
      publish: true
      unpublish: true
      send: true
      update: true
      edit: true
      test: false

      # Disabled for now, as it need the implementation
      sendLater: false
      resend: false
      publishAndSend: false
      unpublishAndUpdate: false

    # job:
    #   transactions:
    #     publishAndSend:
    #       up:
    #         - publish
    #         - send
    #       down:
    #         - unpublish
    #     unpublishAndUpdate:
    #       up:
    #         - unpublish
    #         - update
    #       down:
    #         - publish
