Garagist:
  Mautic:
    routeArgument:
      htmlTemplate: email
      plaintextTemplate: plaintext
    api:
      baseUrl: null
      userName: null
      password: null
      ignoreHttpsErrors: false
    publicUrl: null
    enableTracking: false
    # Can be javascript, iframe, plain or api
    embedType: javascript
    apiRenderer: null
    form:
      # Add here the IDs of the forms you want to hide
      # You can pass an array (eg. [1, 2, 3]) or an integer
      hide: null

    category:
      # Add here the ID of the category you want to use for the newsletter
      newsletter: null

    testMail:
      # Add here the email addresses you want to use for testing
      # You can pass an array (eg. ['test@mail.example', 'user@mail.example']) or an string (eg. 'test@mail.example')
      recipients: null

    # Settings for email segments
    segment:
      # If an segment is prefilled from the creation/edit dialog, the user can't unselect it
      lockPrefilled: true

      # The ID of the segment to use for the newsletter
      # But you can also define an array/object to handle the segment in your own data provider
      mapping: null

      # Add here to segments to choose from on creation/edit dialog
      # You can pass an array (eg. [1, 2, 3]) or an integer, if you have a nested array, the entries are handled as groups
      # choose:
      #   - [1, 2,] <- Is a group, of preselected segments the user gets radio buttons
      #   - 3 <- Is a single segment, the user gets a checkbox
      choose: null

      # Add here the IDs of the segments you want to hide (eg. for unconfirmed contacts)
      # You can pass an array (eg. [1, 2, 3]) or an integer
      hide: null

    action:
      delete: true
      publish: true
      unpublish: true
      send: true
      update: true
      edit: true
      test: false

      # Disabled for now, as it need the implementation
      sendLater: false
      resend: false
      publishAndSend: false
      unpublishAndUpdate: false

    # job:
    #   transactions:
    #     publishAndSend:
    #       up:
    #         - publish
    #         - send
    #       down:
    #         - unpublish
    #     unpublishAndUpdate:
    #       up:
    #         - unpublish
    #         - update
    #       down:
    #         - publish
