Garagist:
  Mautic:
    routeArgument:
      htmlTemplate: emailHtml
      plaintextTemplate: emailPlain
    api:
      baseUrl: null
      userName: null
      password: null
    segmentMapping: []
    # Add here the segment ID of the Mautic segment who contains not confirmed contacts
    unconfirmedSegment: null
