Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          'Garagist.Mautic:MauticLogger':
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/Mautic.log'
                createParentDirectories: true
                severityThreshold: '%LOG_DEBUG%'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Garagist.Mautic:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Garagist.Mautic: true
