Garagist:
  Mautic:
    routeArgument:
      htmlTemplate: emailHtml
      plaintextTemplate: emailPlain
    api:
      baseUrl: null
      userName: null
      password: null
    publicUrl: null
    enableTracking: false
    forms:
      hideIds: []
    # Add here the ID fo the newsletter category
    newsletterCategoryId: null
    segmentMapping: []
    # Add here the segment ID of the Mautic segment who contains not confirmed contacts
    unconfirmedSegment: null
    # Make actions configurable
    jobs:
      transactions:
        publishAndSend:
          up:
            - publish
            - send
          down:
            - unpublish
      actions:
        delete: true
        publish: true
        unpublish: true
        send: true
        update: true
